workspace:
  base: /go
  path: src/github.com/Depado/goploader/

matrix:
  ARCH:
    - arm
    - amd64

pipeline:
  # Ensure dep and rice commands are installed, and use dep for vendoring
  prerequisites:
    image: "golang:1.9"
    commands: 
      - go get -u github.com/golang/dep/cmd/dep
      - go get github.com/GeertJohan/go.rice/rice
      - dep ensure

  # Build the server
  server: 
    image: "golang:1.9"
    group: build
    commands:
      - go build -o server/server ./server
    environment:
      - GOARCH=${ARCH}
      - CGO_ENABLED=0
  
  # Build client
  client:
    image: "golang:1.9"
    group: build
    commands:
      - go build -o client/client ./client
    environment:
      - GOARCH=${ARCH}
      - CGO_ENABLED=0

  # Build docs
  docs:
    image: python:3
    group: build
    commands:
      - cd docs
      - pip install -r requirements
      - mkdocs build
  
  # Release only for the latest stable version of Go
  server-release:
    image: "golang:1.9"
    commands:
      - mkdir goploader-server
      - rice embed-go -i=github.com/Depado/goploader/server
      - go build -o goploader-server/server-standalone github.com/Depado/goploader/server
      - tar czf server-standalone_${ARCH}.tar.gz goploader-server
      - rm -r goploader-server/*
      - rice clean -i=github.com/Depado/goploader/server
      - cp -r server/assets/ server/templates/ goploader-server/
      - go build -o goploader-server/server github.com/Depado/goploader/server
      - tar czf server_${ARCH}.tar.gz goploader-server/
    environment:
      - GOARCH=${ARCH}
      - CGO_ENABLED=0
    when:
      event: deployment


  # Copy the built releases
  server-release-scp:
    image: appleboy/drone-scp
    host: gpldr.in
    username: depado
    target: /home/depado/goploader/releases/servers/
    source:
      - server_${ARCH}.tar.gz
      - server-standalone_${ARCH}.tar.gz
    secrets:
      - source: deploy_key
        target: scp_key
    when:
      status: success
      event: deployment

  # Build the deployable version (embedded assets, 1.9 version and arm arch)
  server-deploy-build:
    image: "golang:1.9"
    group: build
    commands:
      - rice embed-go -i=github.com/Depado/goploader/server
      - go build -o server/server-new github.com/Depado/goploader/server
      - rice clean -i=github.com/Depado/goploader/server
    environment:
      - GOARCH=${ARCH}
      - CGO_ENABLED=0
    when:
      matrix:
        ARCH: arm
      event: deployment

  # Copy the deployable version
  server-deploy-scp:
    image: appleboy/drone-scp
    host: gpldr.in
    username: depado
    target: /home/depado/goploader/new/
    source: ./server/server-new
    secrets:
      - source: deploy_key
        target: scp_key
    when:
      status: success
      matrix:
        ARCH: arm
      event: deployment

  # Executed only when deploying
  client-release:
    image: "golang:1.9"
    commands:
      - go get github.com/mitchellh/gox
      - mkdir clients
      - gox -output="clients/client_{{.OS}}_{{.Arch}}" github.com/Depado/goploader/client
      - tar czf clients.tar.gz clients
    when:
      matrix:
        ARCH: amd64
      event: deployment

  # Executed only once (only one matrix)
  client-release-scp:
    image: appleboy/drone-scp
    host: gpldr.in
    username: depado
    target: /home/depado/goploader/releases/clients/
    source: clients/*
    secrets:
      - source: deploy_key
        target: scp_key
    when:
      matrix:
        ARCH: amd64
      event: deployment

  github-release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: 
      - clients/*
    when:
      event: tag
