build:
  image: armhfbuild/golang:$$GO_VERSION
  commands:
    - go get ./...
    - go build github.com/Depado/goploader/server -o server/server
    - go build github.com/Depado/goploader/client -o client/client
    - go test

matrix:
  GO_VERSION:
    - 1.6
    - 1.5
