workspace:
  base: /go
  path: src/github.com/Depado/goploader/

matrix:
  TAG:
    - 1.8
    - latest

pipeline:
  prerequisites:
    image: golang:${TAG}
    - go get ./...
    - go get github.com/GeertJohan/go.rice
    - go get github.com/GeertJohan/go.rice/rice
  build-server:
    image: golang:${TAG}
    commands:
      - rice embed-go -i=github.com/Depado/goploader/server
      - go build -o server/server ./server
      - go build -o client/client ./client
      - rice clean -i=github.com/Depado/goploader/server
    environment:
      - CGO_ENABLED=0