build:
  image: armhfbuild/golang:$$GO_VERSION
  commands:
    - go get ./...
    - go build -o server/server ./server
    - go build -o client/client ./client 

matrix:
  GO_VERSION:
    - 1.6
    - 1.5

notify:
  irc:
    prefix: build
    nick: drone
    channel: n0sec
    server:
      host: irc.freenode.net
      port: 6667
