workspace:
  base: /go
  path: src/github.com/Depado/goploader/

matrix:
  TAG:
    - 1.9
    - 1.8
  ARCH:
    - arm
    - amd64

pipeline:
  prerequisites:
    image: golang:${TAG}
    commands:
      - go get ./...
      - go get github.com/GeertJohan/go.rice
      - go get github.com/GeertJohan/go.rice/rice
      - go get github.com/mitchellh/gox

  server-build:
    image: golang:${TAG}
    group: build
    commands:
      - go build -o server/server ./server
    environment:
      - GOARCH=${ARCH}
      - CGO_ENABLED=0
  
  client-build:
    image: golang:${TAG}
    group: build
    commands:
      - go build ./client
    environment:
      - GOARCH=${ARCH}
      - CGO_ENABLED=0
  
  # Realse only for the latest stable version of Go
  server-release:
    image: golang:${TAG}
    commands:
      - mkdir goploader-server
      - rice embed-go -i=github.com/Depado/goploader/server
      - go build -o goploader-server/server-standalone github.com/Depado/goploader/server
      - tar czf server-standalone_${ARCH}.tar.gz goploader-server
      - rm -r goploader-server/*
      - rice clean -i=github.com/Depado/goploader/server
      - cp -r server/assets/ goploader-server/
      - cp -r server/templates/ goploader-server/
      - go build -o goploader-server/server github.com/Depado/goploader/server
      - tar czf server_${ARCH}.tar.gz goploader-server/
    environment:
      - GOARCH=${ARCH}
      - CGO_ENABLED=0
    when:
      matrix:
        TAG: 1.9

  server-scp:
    image: appleboy/drone-scp
    host: gpldr.in
    username: depado
    target: /home/depado/goploader/releases/servers/
    source:
      - server_${ARCH}.tar.gz
      - server-standalone_${ARCH}.tar.gz
    secrets:
      - source: deploy_key
        target: scp_key
    when:
      status: success
      matrix:
        TAG: 1.9

  # Executed only once (only one matrix)
  client-release:
    image: golang:${TAG}
    commands:
      - mkdir clients
      - gox -output="clients/client_{{.OS}}_{{.Arch}}" github.com/Depado/goploader/client
      - tar czf clients.tar.gz clients
    when:
      matrix:
        TAG: 1.9
        ARCH: amd64
