site_name: Goploader
site_url: https://gpldr.in
repo_url: https://github.com/Depado/goploader
site_author: Depado
theme: 'material'
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
pages: 
  - Home: index.md
  - Server Guide:
    - Build From Source: server/build.md
    - Downloads: server/downloads.md
    - Setup: server/install.md
    - Running: server/running.md
    - Serve: server/serve.md
  - Client: 
    - Build From Source: client/build.md
    - Downloads and Install: client/install.md
    - Documentation: client/documentation.md
  - Curl: curl.md
extra:
  social:
    - type: 'github'
      link: 'https://github.com/Depado'
    - type: 'twitter'
      link: 'https://twitter.com/Depado_'


